version: '3.8'

services:
    rr_app:
        build:
            context: .
        ports:
            - '8000:8000'
        volumes:
            - ./rr_project:/usr/src/rr_app
        command: >
            sh -c 'python manage.py runserver 0.0.0.0:8000'
        env_file:
            - .env.dev
